### ISSUE TITLE
导出的MIDI错乱；Windows环境下拖动功能无效

### ISSUE THREAD

**Issue by QyInvoLing** [happyme531/GenshinImpactPianoExtract#2]
视频地址https://www.bilibili.com/video/BV1Er4y1C7jd
分辨率1080p，30帧，使用默认参数时导出的midi与原曲完全不一致：具体表现为同一音符被识别多次
猜测可能和视频中有同时按下两个按键的操作有关。

此外，直接将视频拖动至程序上会导致输出失败，使用命令行调用程序时问题解决。

**Comment by happyme531** [comment]
视频链接挂了... 把文件直接发过来吧

**Comment by happyme531** [comment]
拖动输出失败可能是由于路径中有空格或者是特殊字符, 目前我也观察到了这个问题, 但是只是报错, 实际文件可以正常输出

**Comment by QyInvoLing** [comment]
[video](https://wwa.lanzoui.com/isTraw38agj)

**Comment by happyme531** [comment]
只能说检测算法还是不太完善。。。

**Comment by happyme531** [comment]
v0.1.3版本应该解决了
