### ISSUE TITLE
读取的midi存在多重复一次的bug

### ISSUE THREAD

**Issue by 994346680** [happyme531/GenshinImpactPianoExtract#3]
并没有看代码，只是猜测进行了视频拆帧。
观察得到的结论是，30帧的视频，按一次按键至少“白”了两次，也就是会亮两帧，读取得到的midi也全部重音，导致生成的音符重复且混杂。

**Comment by 994346680** [comment]
希望bug能修，因为这个项目很棒，大佬很厉害，而我玩不懂midi。

**Comment by happyme531** [comment]
能上传一下出现问题的原视频吗？

**Comment by 994346680** [comment]
材料：均在某站下载片源，1080 30，单视频轨无音频，视频2进行了剪切跳过开场。视频1（BV1YY4y1c7Bq）视频2（BV1j34y1m7xf）单个视频轨60mb大于25mb传不了，分别是脚本弹奏和人手弹奏。
测试脚本：性能强大的 [genshin-musician](https://github.com/YuehaiTeam/genshin-musician)
武器：风物之诗琴
结果：生成的2个midi 均可复现。[mid.zip](https://github.com/happyme531/GenshinImpactPianoExtract/files/14011876/mid.zip)

**Comment by happyme531** [comment]
> 材料：均在某站下载片源，1080 30，单视频轨无音频，视频2进行了剪切跳过开场。视频1（BV1YY4y1c7Bq）视频2（BV1j34y1m7xf）单个视频轨60mb大于25mb传不了，分别是脚本弹奏和人手弹奏。 测试脚本：性能强大的 [genshin-musician](https://github.com/YuehaiTeam/genshin-musician) 武器：风物之诗琴 结果：生成的2个midi 均可复现。[mid.zip](https://github.com/happyme531/GenshinImpactPianoExtract/files/14011876/mid.zip)

这两个midi文件在我这里看起来/听起来都没有任何问题。是不是脚本的bug?

**Comment by 994346680** [comment]
[Genshin_Zither_Player](https://github.com/WitchElaina/Genshin_Zither_Player)读文字谱
问题midi读出的文字谱是这样的：
1 jv q vj
2 wa qe wa ded te tbe bssg
正常midi[【原神适配】起风了-赵日天制作.zip](https://github.com/happyme531/GenshinImpactPianoExtract/files/14019542/-.zip)读出来的是这样的：
1 vgj q aw ed gte baq
可以看到 vj q wa te 都有重复

可能你的脚本是两帧实时弹奏，重合一起了吧。性能太好了属于是（？
算了无所谓了，同个文件在不同脚本的播放效果也不一样，各位大佬读取方式各显神通，midi制作也没有什么规范，讲求一个百花齐放。反正也没有人听我弹琴，玩了两天就腻了，无所谓了，大佬不用费心了。

**Comment by happyme531** [comment]
这是脚本的bug，NOTE_ON但velocity=0的音符应该按NOTE_OFF处理
https://github.com/WitchElaina/Genshin_Zither_Player/blob/96f1a5e7698ffb2c5de70234db8d7d6698a1b12a/GenshinZitherPlayer.py#L71C1-L86C1
参考：
https://github.com/happyme531/clxTools/commit/5ba62947205a7783ba15a620974e7883b8a71701

**Comment by happyme531** [comment]
https://github.com/craigsapp/midifile/issues/25#issuecomment-254874125
